
name: tests
on: [push, pull_request]
jobs:
  module:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ğŸ›ï¸ graph-compiler
        uses: actions/checkout@v2
        with:
          path: graph-compiler
          persist-credentials: false
          submodules: 'recursive'

      - name: Run Tests
        run: |
          cd graph-compiler
          docker run --rm -v `pwd`:/ivy/graph-compiler unifyai/ivy:latest graph-compiler/tests/scripts/test_module.sh
